---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: porch-controllers-rootsyncdeployments
rules:
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - rootsyncdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - rootsyncdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - config.porch.kpt.dev
  resources:
  - rootsyncdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configcontroller.cnrm.cloud.google.com
  resources:
  - configcontrollerinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - container.cnrm.cloud.google.com
  resources:
  - containerclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.cnrm.cloud.google.com
  resources:
  - configconnectorcontexts
  - configconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gkehub.cnrm.cloud.google.com
  resources:
  - gkehubmemberships
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  verbs:
  - get
  - list
  - watch
