---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: porch-controllers-klippy
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisions/status
  verbs:
  - get
  - patch
  - update
